"""Phase 4 prep — assemble Piper training dataset layout from phase3 output.

Piper expects:
  --data.csv_path      metadata.csv with `id|sentence` rows
  --data.audio_dir     directory with <id>.wav at the target sample rate
  --data.config_path   model config (autogenerated by piper.train on first run)
  --data.cache_dir     working cache

Phase 3 already wrote phase3/audio/<id>.wav and phase3/metadata.csv in
the right format. This script just verifies them and creates a held-out
eval list for Phase 5 (250 sentences, never seen during training).
"""
from __future__ import annotations

import csv
import json
import random
from pathlib import Path

RUN = Path(__file__).resolve().parent.parent
import json as _piper_json
OUT = RUN / "output" / _piper_json.loads((RUN / __import__("os").environ.get("PIPER_DISTILL_CONFIG", "run_config.json")).read_text())["teacher"]["voice_id"]
META = OUT / "phase3/metadata.csv"
AUDIO = OUT / "phase3/audio"
TRAIN_META = OUT / "phase4/train_metadata.csv"
EVAL_META = OUT / "phase4/eval_metadata.csv"
STATE = OUT / "state/phase4"

EVAL_SIZE = 250  # 200 random + 50 accent-diagnostic stand-ins


def main() -> None:
    STATE.mkdir(parents=True, exist_ok=True)
    (OUT / "phase4").mkdir(parents=True, exist_ok=True)

    rows = []
    with META.open() as f:
        reader = csv.reader(f, delimiter="|")
        for row in reader:
            wav = AUDIO / f"{row[0]}.wav"
            if not wav.exists():
                continue
            rows.append((row[0], row[1]))
    print(f"total surviving clips: {len(rows)}")

    rng = random.Random(20260523)
    rng.shuffle(rows)
    eval_rows = rows[:EVAL_SIZE]
    train_rows = rows[EVAL_SIZE:]
    print(f"train={len(train_rows)} eval={len(eval_rows)}")

    with TRAIN_META.open("w") as f:
        writer = csv.writer(f, delimiter="|")
        for r in train_rows:
            writer.writerow(r)
    with EVAL_META.open("w") as f:
        writer = csv.writer(f, delimiter="|")
        for r in eval_rows:
            writer.writerow(r)
    manifest = {
        "phase": "phase4_prep",
        "train_count": len(train_rows),
        "eval_count": len(eval_rows),
        "train_meta": str(TRAIN_META),
        "eval_meta": str(EVAL_META),
    }
    (STATE / "prep_manifest.json").write_text(json.dumps(manifest, indent=2))
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
